events {
    worker_connections 1024;
}

http {
    upstream cluster_nodos {
        server nodo1:8000;
        server nodo2:8000;
        server nodo3:8000;
    }

    # Reintentar en otro nodo si el seguidor rechaza la escritura (503)
    proxy_next_upstream error timeout http_503;
    proxy_next_upstream_tries 3;

    # HTTP (para pruebas locales sin certificado verificado)
    server {
        listen 80;
        server_name localhost;
        location / { include /etc/nginx/nginx-location-common.conf; }
    }

    # Servidor HTTPS
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/selfsigned.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / { include /etc/nginx/nginx-location-common.conf; }
    }
}
